# Generated by Django 4.1.13 on 2024-03-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LocationData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=100)),
                ("ride_id", models.IntegerField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("speed", models.FloatField()),
                ("timestamp", models.IntegerField()),
                ("movement_angle", models.FloatField()),
                ("address_short", models.CharField(max_length=250, null=True)),
                ("address_full", models.CharField(max_length=250, null=True)),
                (
                    "address_region_type_full",
                    models.CharField(max_length=250, null=True),
                ),
                ("address_region", models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProfileData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=100, unique=True)),
                ("age", models.IntegerField(null=True)),
                ("licence_number", models.CharField(max_length=100, null=True)),
                ("sex", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RideData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ride_id", models.IntegerField()),
                ("uuid", models.CharField(max_length=100)),
                ("auto_start", models.BooleanField()),
                ("auto_finish", models.BooleanField()),
                ("max_speed", models.FloatField()),
                ("min_speed", models.FloatField()),
                ("light_nighttime", models.FloatField()),
                ("nighttime", models.FloatField()),
                ("detected_role", models.CharField(max_length=50)),
                ("selected_role", models.CharField(max_length=50, null=True)),
                ("weather", models.JSONField()),
                ("dangerous_shifts", models.JSONField()),
                ("dangerous_accelerations", models.JSONField()),
                ("speeding", models.JSONField()),
            ],
        ),
    ]
