# Generated by Django 4.1.13 on 2024-03-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ridedata",
            name="address",
            field=models.JSONField(
                default={
                    "address_full": "г Москва",
                    "address_region": "Москва",
                    "address_region_type_full": "город",
                    "address_short": "г Москва",
                }
            ),
        ),
        migrations.AddField(
            model_name="ridedata",
            name="end_timestamp",
            field=models.IntegerField(default=1710429536),
        ),
        migrations.AddField(
            model_name="ridedata",
            name="start_timestamp",
            field=models.IntegerField(default=1710335876),
        ),
    ]
